# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanggapan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggapanTwitter', models.TextField()),
                ('tanggapanSkype', models.TextField()),
                ('created_date_Twitter', models.DateTimeField(auto_now_add=True)),
                ('created_date_Skype', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
