# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitur_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengguna', models.CharField(default='not-set', max_length=100, null=True)),
                ('title', models.CharField(default='not-set', max_length=140, null=True)),
                ('message', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
