# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default='not-set', max_length=400, primary_key=True, serialize=False)),
                ('profilePic', models.CharField(default='not-set', max_length=400, null=True)),
                ('name', models.CharField(default='not-set', max_length=400, null=True)),
                ('desc', models.CharField(default='not-set', max_length=500, null=True)),
                ('companyType', models.CharField(default='not-set', max_length=100, null=True)),
                ('website', models.URLField(null=True)),
                ('specialities', models.CharField(default='not-set', max_length=100, null=True)),
                ('address', models.CharField(default='not-set', max_length=100, null=True)),
            ],
        ),
    ]
